name: 刷步数

on:
  schedule:
    #- cron: '16 0,2,4,6,8 * * *'
    - cron: '05 23 * * *'  # 07:05
    - cron: '42 0 * * *'   # 08:42
    - cron: '18 2 * * *'   # 10:18
    - cron: '56 3 * * *'   # 11:56
    - cron: '31 5 * * *'   # 13:31
    - cron: '07 7 * * *'   # 15:07
    - cron: '44 8 * * *'   # 16:44
    - cron: '21 10 * * *'  # 18:21
    - cron: '58 11 * * *'  # 19:58
    - cron: '35 13 * * *'  # 21:35
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout codes
        uses: actions/checkout@v5

      - name: Update system and install zsh
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get install zsh -y
        
      - name: 初始化Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
          
      - name: 开始
        env:
            CONFIG: ${{ secrets.CONFIG }}
            AES_KEY: ${{ secrets.AES_KEY }}
        run: |
          pip3 install requests pytz pycryptodome
          python3 main.py

      - name: persist tokens
        run: |
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com
          git add .
          git diff --cached --quiet || git commit -m "persist tokens trigger by ${{ github.event_name }}"
          git push origin master
